### ISSUE TITLE
GIF not animated

### ISSUE THREAD

**Issue by anderer** [automadcms/automad-dist#2]
I am using the standard-V1 template.

In the V1 automad a gif of 150 kb is animated.
In the V2 automad the same gif is not animated.

this has also been noted in the discussion section before - https://github.com/orgs/automadcms/discussions/18

**Comment by marcantondahmen** [comment]
Hi, the handling of animated GIFs didn't change in version 2. In both versions, resized images are never animated for performance reasons. This also already has been answered in the discussion thread mentioned above.

All animated GIFs that are resized by a template or block will no longer be animated since only the first frame of the animation will be resized.

Please note that this is only the distribution mirror repository and issues should be only opened in the main repository as described in the README here.
